### ISSUE TITLE
ConcurrentModificationException: null

### ISSUE THREAD

**Issue by rendro** [KnisterPeter/smaller-dev-server#11]
2014-02-20 19:59:32,194  [qtp745108863-61] ERROR d.m.smaller.dev.server.Servlet - Failed to handle request
java.util.ConcurrentModificationException: null
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859) ~[na:1.7.0_45]
    at java.util.ArrayList$Itr.next(ArrayList.java:831) ~[na:1.7.0_45]
    at de.matrixweb.vfs.scanner.VFSResourceLister.list(VFSResourceLister.java:35) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.vfs.scanner.ResourceScanner.findRecursive(ResourceScanner.java:79) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.vfs.scanner.ResourceScanner.findRecursive(ResourceScanner.java:81) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.vfs.scanner.ResourceScanner.filterRecursive(ResourceScanner.java:92) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.vfs.scanner.ResourceScanner.findCandidates(ResourceScanner.java:63) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.vfs.scanner.ResourceScanner.getResources(ResourceScanner.java:45) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.smaller.dev.server.SmallerResourceHandler.hasFile(SmallerResourceHandler.java:262) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.smaller.dev.server.Servlet.findEnvironmentByFile(Servlet.java:295) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.smaller.dev.server.Servlet.handleProxyRequest(Servlet.java:158) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.smaller.dev.server.Servlet.handleHttpRequest(Servlet.java:119) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.smaller.dev.server.Servlet.doGet(Servlet.java:91) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:734) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.websocket.WebSocketServlet.service(WebSocketServlet.java:80) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:558) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:488) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:973) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:417) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:907) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.Server.handle(Server.java:350) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:442) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:582) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]

**Comment by KnisterPeter** [comment]
Belongs into VFS
