### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by unstubbable** [KnisterPeter/smaller-dev-server#15]
When the server is running for while I sometimes get an OutOfMemoryError:

```
2014-04-01 12:43:11,804  [qtp2026433662-133] WARN  o.e.jetty.servlet.ServletHandler - Error for /frontend/foo.js
java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:2367) ~[na:1.7.0_25]
    at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130) ~[na:1.7.0_25]
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114) ~[na:1.7.0_25]
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:535) ~[na:1.7.0_25]
    at java.lang.StringBuilder.append(StringBuilder.java:204) ~[na:1.7.0_25]
    at de.matrixweb.vfs.internal.IOHelper.toString(IOHelper.java:112) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.vfs.VFSUtils.readToString(VFSUtils.java:88) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.smaller.dev.server.SmallerResourceHandler.process(SmallerResourceHandler.java:252) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.smaller.dev.server.Servlet.handleHttpRequest(Servlet.java:135) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at de.matrixweb.smaller.dev.server.Servlet.doGet(Servlet.java:112) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:734) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.websocket.WebSocketServlet.service(WebSocketServlet.java:80) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:558) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:488) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:973) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:417) [smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:907) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.Server.handle(Server.java:350) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:442) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:924) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:582) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533) ~[smaller-dev-server-0.3.1-SNAPSHOT.jar:na]
    at java.lang.Thread.run(Thread.java:724) ~[na:1.7.0_25]
```

**Comment by KnisterPeter** [comment]
How big is /frontend/foo.js?

**Comment by KnisterPeter** [comment]
And please try to start the dev server with the option '-Xmx1024M' or '-Xmx2048M'
